### ISSUE TITLE
shop broken after I tried to upgrade your plugin 

### ISSUE THREAD

**Issue by Orgoth** [FriendsOfShopware/FroshPlatformMailArchive#87]
### PHP Version

8.2.20

### Shopware Version

dont know, since I can not access the shop anymore

### Plugin Version

dont know, since I can not access the shop anymore

### Actual behaviour

upgrade destroyed the shop!
frontend and backend only 500 server error
shell:
PHP Warning:  require(/var/www/filterdealer/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): Failed to open stream: No such file or directory in /var/www/filterdealer/vendor/composer/autoload_real.php on line 41
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/filterdealer/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/usr/share/php') in /var/www/filterdealer/vendor/composer/autoload_real.php:41
Stack trace:
#0 /var/www/filterdealer/vendor/composer/autoload_real.php(45): {closure}()
#1 /var/www/filterdealer/vendor/autoload.php(25): ComposerAutoloaderInit5fc316c920d2c1417be36a3c639f540c::getLoader()
#2 /var/www/filterdealer/vendor/autoload_runtime.php(5): require_once('...')
#3 /var/www/filterdealer/bin/console(17): require_once('...')
#4 {main}
  thrown in /var/www/filterdealer/vendor/composer/autoload_real.php on line 41

### Expected behaviour

clean update without any critical issues

### Steps to Reproduce?

I simply clicked on the update button within the shopware admin interface

this is the error which is thrown when calling the cli

**Comment by tinect** [comment]
Hi,
we cannot reproduce any issue. additionally, the issue seems to be unrelated to the plugin.

It sounds like, the composer or vendor has been manipulated manually.
Please check the project, opcache and named files/folders.

**Comment by Orgoth** [comment]
The composer.json was not edited manually, as it is a new installation from 04.05, which has not received any updates to date.
Only today I clicked on the link to update your plugin and then nothing worked anymore!

To get it working again, I had to manually run composer to continue the update process that got stuck on your plugin.
I then had to uninstall the plugin including all the data in the store and reinstall it so that the latest version could be installed.
It was impossible via the backend of the store.

The next new problem is that the messages are displayed as pending, even though they have already been sent and arrived!

![2024-09-25 18_51_59-Window](https://github.com/user-attachments/assets/c650e014-fc48-4542-9805-8c92415d8a6d)
![2024-09-25 18_51_14-Window](https://github.com/user-attachments/assets/d28d1de0-5fb3-4ce8-aacb-f3a855f026a5)

I should probably have stayed with version 6.5 after all, only problems since 6.6.
Thanks for checking anyway.

**Comment by tinect** [comment]
@Orgoth sounds related to the already open issue.
